In [1]:
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("distilgpt2") 

model = AutoModelForCausalLM.from_pretrained("distilgpt2", output_hidden_states=True)

The following generation flags are not valid and may be ignored: ['output_hidden_states']. Set `TRANSFORMERS_VERBOSITY=info` for more details.


Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: distilgpt2
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
transformer.h.{0, 1, 2, 3, 4, 5}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [2]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

sequence = "The Shawshank"
tokens = tokenizer.tokenize(sequence)

print(tokens)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

C:\Users\JT\.venv\lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\JT\.cache\huggingface\hub\models--bert-base-cased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

['The', 'Shaw', '##shan', '##k']


In [3]:
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")

sequence = "The pilgrimage"
tokens = tokenizer.tokenize(sequence)

print(tokens)
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

['The', 'Ġpilgrimage']
[464, 36068]


In [4]:
# Tokenize the input string
input = tokenizer.encode(sequence, return_tensors="pt")
print(input)


tensor([[  464, 36068]])


In [5]:

# Run the model
output = model.generate(input, max_length=5, do_sample=False)



The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


In [6]:
output

tensor([[  464, 36068,   284,   262,  7439]])

In [7]:
# Print the output
print('\n',tokenizer.decode(output[0]))


 The pilgrimage to the Holy


In [8]:
# Print the token ides (of the input and output)
output

tensor([[  464, 36068,   284,   262,  7439]])

## From words to vectors and back

In [9]:
# Print the input token ids
text = "The Shawshank"
input = tokenizer(text, return_tensors="pt")['input_ids']
input

tensor([[  464, 18193,  1477,   962]])

In [10]:
tokenizer.convert_ids_to_tokens(input[0])

['The', 'ĠShaw', 'sh', 'ank']

## Breathe meaning into numbers (Embedding)

In [11]:
# This is the embedding matrix of the model
model.transformer.wte # Dimensions are: (Number of tokens in vocabulary, dimension of model)

Embedding(50257, 768)

In [12]:
# Get the embedding vector of token # 464 ('The')
model.transformer.wte(torch.tensor(464))

NameError: name 'torch' is not defined

In [ ]:
text = "The chicken didn't cross the road because it was"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=20, do_sample=True)

# Print the output
print('\n',tokenizer.decode(output[0]))